### ISSUE TITLE
Claim reward but hCaptcha can't load

### ISSUE THREAD

**Issue by mylamour** [pk910/PoWFaucet#11]
Hi, man, thanks you provide a faucet to people. and i have a question about the workflow. here it is.

once claimed the reward without load the hCaptcha, it caused another 10 mins wasted. i'm wonder if i passed the hCaptcha at the first time to mining, why i need to do that again when i start to claim? also there was no way to recover the session. 

i know that's not the project's problem, most time it caused by network for captcha validation.   but if there was a way to make it more easier,  i think it would be make this project great.

**Comment by pk910** [comment]
Heya @mylamour 
Thanks for your report.

The reason for the second captcha is that I'd like to prevent unattended mining on unowned devices.
I've described that in more detail here: https://github.com/pk910/PoWFaucet/issues/4

If I understood your report correctly, you're facing issues with the hCaptcha, so you haven't been able to "click" it?
In that case you can simply refresh the page. 
The faucet stores all relevant session information in your browser, so nothing is lost on refresh and you should just see the claim dialog again.

Send me your address and I'll send you the missed rewards manually :)

**Comment by mylamour** [comment]
thanks man @pk910  ,  i'm already got the test token from friends quickly.  in additional,  i read the the #4 , and i have to say sometimes you can mining it in Safari in few minutes, sometimes you will wasted few hours. and i was try to use chrome, and i increased the thread then i have to restart the computer.  i believe there should be another way to build a friendly faucet.   Here is some advice :

1. integrated with account system to login. for example: user can login with Github account directly.
2. limited to send . for example: each account can get 0.5 max each day and each hour get 0.1
3. use CDN to prevent your website from spam. for example: use Cloudflare , also you can use rate limiter features.

that will improve the quality.

**Comment by pk910** [comment]
Thanks for your suggestions, but I don't really want to go that way.

It's kind of a feature that you don't need to create an account on my faucet and everyone can simply request small amounts by mining some minutes. (... or hours if you need more)

Unfortunately accounting doesn't solve the distribution problem in any way. 
Farmers would simply mass-register accounts and use these to drain the faucet...
Technically it also simplifies operating the faucet as there is no backend database / mails system / etc. involved :)


Btw. What you describe is basically the alchemy faucet ;)
-> [Alchemy Goerli Faucet](https://goerlifaucet.com/)
