### ISSUE TITLE
I keep failing the captcha 

### ISSUE THREAD

**Issue by AhyanSch** [pk910/PoWFaucet#128]
I keep failing the captcha, after i had mined for over an hour.

**Comment by pk910** [comment]
Sorry to hear, I hope you've been able to claim your reward in meantime.
You could try reloading the page if it keeps failing.

**Comment by Makscrypto91** [comment]
I received completely 2.5 Eth

Il Lun 19 Feb 2024, 06:00 pk910 ***@***.***> ha scritto:
