### ISSUE TITLE
Boost Score (Passport) not applied sometimes

### ISSUE THREAD

**Issue by pk910** [pk910/PoWFaucet#13]
There is currently an issue with fetching the gitcoin passport scores.

About 40-60% of the refresh requests fail due to empty/malformed responses.
I guess my faucet is being rate limited, as there are too many requests...

Workaround for now: 
Refresh your Gitcoin Passport manually from the faucet UI if the score is not applied correctly.

**Comment by ss22219** [comment]
Hi, I tried manually refresh my Gitcoin Passport many times, but it still shows Boost Score 0.
My address: 0xbF30b5020F1C8A00EE03ea8326D360C7b6883662

**Comment by pk910** [comment]
Heya @ss22219,
I've manually checked for 0xbF30b5020F1C8A00EE03ea8326D360C7b6883662, but didn't get back any verification stamps,
Did you verify a few of the stamps on https://passport.gitcoin.co/#/dashboard ?
Be aware that you need to connect to the same wallet for your passport as you're mining for :)

**Comment by ss22219** [comment]
Yes, I did several verification stamps a few days ago, here is the downloaded file
[passport.zip](https://github.com/pk910/PoWFaucet/files/10917927/passport.zip)

**Comment by pk910** [comment]
Uhm, yea..  Great how well that passport stuff does...
I'm still not getting anything for your address via their verification sdk...

Guess I have to rework the implementation 😒
Probably have to add a input form to paste in the json manually in case it cannot be refreshed automatically..
But then I'd also have to save it somewhere, or it'd need to be uploaded for each session...

**Comment by ss22219** [comment]
Well, that's their sdk problem, thank you 😀

**Comment by pk910** [comment]
@ss22219 
I've implemented a manual passport verification with 05f8895
You should be able to send in your passport JSON manually for verification :)

Passports are stored locally on the faucet server, so this should only be necessary to add stamps or so, but not for every session.

I think this should solve the overall issue with missing passport scores. 
Well, not really solved it, but it's at least a workaround ;)

**Comment by ss22219** [comment]
@pk910 I tried it and it worked perfectly!

**Comment by pk910** [comment]
Closing this issue as I think the manual verification is a suitable way to refresh the score in case the automatic refresh doesn't work :)

**Comment by Mouradif** [comment]
So manual verification should always be used even if the automatic one shows correct numbers?

In that case, the fix for this issue would be to reflect that on the UI. Otherwise, the only way to know this is to find this issue in the repo

**Comment by pk910** [comment]
> So manual verification should always be used even if the automatic one shows correct numbers?

No. If the automatic refresh shows you the right numbers, there is no need to use the manual stuff.
The manual verification is a workaround for the situation where the automatic one does not work for some strange reason ;)
