### ISSUE TITLE
mining rate is little slow

### ISSUE THREAD

**Issue by Ratty87** [pk910/PoWFaucet#133]
there is wait to mine

**Comment by pk910** [comment]
Sorry, I don't really understand your request.
The PoW Faucets have a fixed daily outflow limit (30k HolETH & 5k SepETH per day), the mining difficulty / rewards get adjusted automatically to meet that limit.
The more people are mining, the harder the algorithm gets. This is the intended behavior of the faucet to avoid bot attacks.
