### ISSUE TITLE
Why didn't I receive the token after running the faucet

### ISSUE THREAD

**Issue by zhuszqwe** [pk910/PoWFaucet#15]
Why didn't I receive the token after running the faucet

**Comment by pk910** [comment]
I don't know ¯\_(ツ)_/¯
If you share some details (eg. your wallet address), I can look it up ;)

**Comment by raaffee** [comment]
0x2c96588170E86713501cE5577425D794cE1AB64b

**Comment by pk910** [comment]
Heya,

I've found quite many sessions for your address in the past 10 days ;)
Seems like all running fine and it's not throttled in any way. But your mining hashrate is very very low (~50 H/s). 
The average mining speed I see from other users is about 200-300H/s.

I also see that you've been mining for about a hour in your last session, but the reward was still exactly 0 at the end.
I'm not tracking session progress very closely, so I can't tell you what exactly happened during your session.

But by the numbers I see, I guess that you had a very very unstable internet connection while mining?
Disconnects and a huge delay could lead to reward penalties, which accumulate with each interruption.
(That's unfortunately technically necessary to mitigate a DoS vector against the faucet)

Given these points (slow mining speed & slow network with interruptions) I guess that you're mining on your phone or tablet?
The faucet is not really designed to be used on such devices and I don't think I can help you to improve your rewards...

Did you already try some of the other faucets? -> https://faucetlink.to/goerli

**Comment by raaffee** [comment]
Ok thank you
