### ISSUE TITLE
GnosisSafe is not providing a passport score

### ISSUE THREAD

**Issue by TundraFizz** [pk910/PoWFaucet#16]
My passport score remained the same after verifying my GnosisSafe, and the number is blank where it would be showing me how many points I would get from it

![image](https://user-images.githubusercontent.com/7051693/224828263-830f56ca-0198-4424-a3ee-1dc444e4b9a0.png)

**Comment by pk910** [comment]
Heya @TundraFizz,

Thanks very much for reporting this :)

There is indeed a score value missing for this stamp.
I've added it with a +2 score (same as ENS because deploying such a Gnosis Safe requires paying some fee on mainnet too)
