### ISSUE TITLE
hashrate not showing after some update on 13/03/2023

### ISSUE THREAD

**Issue by thangtrinh34** [pk910/PoWFaucet#17]
![image](https://user-images.githubusercontent.com/73822233/224862096-67a90add-b754-4e9b-b4e6-8113daf5c15f.png)
before update my hashrate alway 0.05/h and now no income. What is happening sir, sorry my spam

**Comment by pk910** [comment]
Yea, had some problems with the farmer detection...
Some sessions were "blacklisted" accidentally.
I hope it's resolved now,  but still monitoring it to be sure.

**Comment by thangtrinh34** [comment]
thank sir, i saw my hashrate is increase again, my pc is weak so back to my old hashrate make me happy again :D
because my average reward around 0.05/h, sorry, this exactly is "my average reward" not "hashrate"
