### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by warengonzaga** [pk910/PoWFaucet#18]
I'm curious, here are my questions.

1. What does it do in the background while waiting?
2. What's Proof of Work mean here? Do I contribute to something? (I mean I know what PoW is, I'm confused)
3. Also if I create my own, do I need a huge amount of funds for the specific testnet?

Sorry to be a pain, but I'm really curious about what does it. Maybe add more info to the repo.

**Comment by warengonzaga** [comment]
That is the perfect explanation! I thought the same in the first place: the PoW stands for doing the same but for faucet setup. So the client is currently in contact with the server while doing the computation? I noticed that when I lock my machine it stops which is perfect because that is intended. I mean "PoW" you need to do something to get the reward.

Looking forward to donating hash power to get some funds from the faucet.

**Comment by pk910** [comment]
Yea, the client is in contact with the server all the time.
In theory that wouldn't be necessary, but there are 2 reasons why I'm doing that:
1. The inputs/hashes that are received from clients need to be verified somehow, or bad players could just send in random numbers.
Unfortunately that means, that the server needs to do some computation work to verify the hashes, too.
As that could lead to a very high load on server side (there are >2k concurrent sessions at peak), I'm not doing this verification on the server.
Instead, the faucet redistributes these hashes to other clients that are mining at the same time.
These randomly selected clients (2 for each hash) do the verification and return the validity result to the server.
The server just compares if the clients agree on the result, but doesn't need to work on the hashing stuff itself.
The verifying clients are rewarded for doing these verifications too, which gives very slow miners some reward too (makes it even more fair)
I need to keep clients connected to be able to send them something for verification anytime.
2. Unfortunately PoW isn't as fair as it felt like in my head when staring this faucet...
There are some users that were spinning up hundreds of machines to mine on my faucet.
As that wasn't "fair" in regards of slower miners anymore, I had to add some IP-Based restrictions.
These restrictions only work reliably when keeping the clients connected all the time.

To mitigate issues with unstable internet connections, you may interrupt the connection for up to 30mins ;)
The client just continues mining and sends in all hashes it found during the offline-time as soon as it connects again.

**Comment by Verity65** [comment]
good

**Comment by tranthanh71** [comment]
Good project

**Comment by nopoxoBHuk** [comment]
Why was Russia banned? Crypt without politics. It looks like fascism from your side!

**Comment by pk910** [comment]
I'm legally not allowed to export anything valuable to the Russian federation.
That's due to known restrictions and isolation attempts, that I won't break for some ideology you don't share at all.

I'm also not gonna argue with that at all. My family is personally affected by what your country is doing to their neighborhood.
So Russian IP's are not welcome on ANY of my services, which includes this faucet. I'm gonna delete all further comments that try to critic this.

**Comment by nopoxoBHuk** [comment]
dm twiter
