### ISSUE TITLE
There are too few rewards for the same hashrate on macmini

### ISSUE THREAD

**Issue by strahe** [pk910/PoWFaucet#185]
Hi, thank you for providing such a good tool.
I tried to mine HolETH on two machines, one is my intel laptop (office), and the other is my macmini m1(home). 
No matter how I try, the reward of macmini is always lower than that of my laptop (with the same hashrate, I can only get 10% reward or even less), I have tried several times with the same result, and I don’t know if any restrictions have been triggered.

![intel laptop](https://github.com/pk910/PoWFaucet/assets/7932644/cd385e29-75b1-4c56-a147-560f71997eda)
intel laptop

![macmini](https://github.com/pk910/PoWFaucet/assets/7932644/3443a50e-ba68-4507-855a-a2bb091cd91e)
macmini m1

**Comment by pk910** [comment]
Heya @strahe, 

Yea, there seems to be some protection kicking in.
According to the numbers it looks like your IP was marked as proxy range by https://ip-api.com

Normally there should be a warning shown if the IP is flagged.. 
I'm looking into it to see why this is not the case here.

**Comment by strahe** [comment]
Thank you for your reply.
In fact, I did use the same proxy in both environments, it should be the same IP, anyway, it seems normal now.
