### ISSUE TITLE
It couldn't load the page github faucet

### ISSUE THREAD

**Issue by VAKaiden** [pk910/PoWFaucet#208]
Hello,
Wen I tryed open https://github-holesky-faucet.pk910.de/ it couldn't load the page.
I got the state (see below)
![image](https://github.com/pk910/PoWFaucet/assets/124048638/ea3f8715-0957-4921-bbb1-b9e4a50b063d)

Console:
![image](https://github.com/pk910/PoWFaucet/assets/124048638/061b6ae3-122d-4298-9a55-5c99984dfaa6)

@pk910 could you please explain where the reason?

**Comment by pk910** [comment]
Yea, it's dead. Github suspended the Github authentication as it leads to fake account which they don't want and is against their AGB.
