### ISSUE TITLE
can't load captcha

### ISSUE THREAD

**Issue by tron123321** [pk910/PoWFaucet#211]
![Snipaste_2024-04-23_14-51-37](https://github.com/pk910/PoWFaucet/assets/70424681/f5497f9d-9875-42de-8959-3ef150ca4867)

**Comment by pk910** [comment]
Heya @tron123321,
Thanks for your report.

I unfortunately can't reproduce as the captcha is loading for me.
Can you open the developer console (F12) and check if there are any errors displayed for the page?

**Comment by tron123321** [comment]
Thanks.
Maybe it's my network problem.
