### ISSUE TITLE
Error: Captcha could not be loaded

### ISSUE THREAD

**Issue by ndcc5** [pk910/PoWFaucet#212]
![image](https://github.com/pk910/PoWFaucet/assets/6286019/67360556-1a72-4de3-9fcd-8e7b45da4109)

**Comment by tron123321** [comment]
me too

**Comment by Frantz09** [comment]
me too

**Comment by pk910** [comment]
Thanks for your reports.

I unfortunately can't reproduce as the captcha is loading for me.
Can you provide more information? what instance are you trying to use? which browser is used?
And please open the developer console (F12) and check if there are any errors displayed for the page?

**Comment by pvnotpv** [comment]
custom captcha could not be initialized; in console dev tools

**Comment by pk910** [comment]
Can you provide more information? what instance are you trying to use? which browser is used?
Any VPN or Proxy server in use?

**Comment by jpx** [comment]
I was able to reproduce a similar issue, with the following logs:

```
captchaScript.php?fa…ustomCaptcha9440:34 
 GET https://challenges.cloudflare.com/turnstile/v0/api.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 403 (Forbidden)

```

![image](https://github.com/pk910/PoWFaucet/assets/1085293/a8aea85d-fe83-4205-b73f-487ebba3aea2)

No VPN nor proxy, with Brave 1.65.123.
