### ISSUE TITLE
Could not start session

### ISSUE THREAD

**Issue by userwilliams45** [pk910/PoWFaucet#213]
Couldnt use faucet 
![Screenshot (96)](https://github.com/pk910/PoWFaucet/assets/33026843/12247cd1-fc87-4fa1-b611-42b9941bc38f)

**Comment by pvnotpv** [comment]
yep I'm also having the same issue, also the captcha is not being loaded

**Comment by pk910** [comment]
Heya @userwilliams45

It looks like your IP is flagged to be part of a datacenter range by https://ip-api.com/
Are you using some kind of proxy or VPN? If so, disable that when using the faucet.
If not, please check ip-api.com to see if your IP is really marked as `"hosting": true`

**Comment by userwilliams45** [comment]
I checked hosting is checked as true... Whats the way forward

**Comment by pk910** [comment]
Heya,
I'm unfortunately unable to remove that protection completely as it leads to mass mining from cloud machines when removed.

However, I've implemented a way to bypass the hosting & proxy check by proving the identity via gitcoin passport.
There should be a new popup coming up when connecting from a IP that is marked as proxy or hosting range.
Please check if that works for you. You'll need a minimum score of 10, which should be easily reachable :)

New version is live on the holesky instance only.

**Comment by SandeepKumar58** [comment]
Heya,
I'm unfortunately unable to remove that protection completely as it leads to mass mining from cloud machines when removed.

However, I've implemented a way to bypass the hosting & proxy check by proving the identity via gitcoin passport.
There should be a new popup coming up when connecting from a IP that is marked as proxy or hosting range.
Please check if that works for you. You'll need a minimum score of 10, which should be easily reachable :)

New version is live on the holesky instance only.

**Comment by pk910** [comment]
That's what I said :P
