### ISSUE TITLE
开始挖矿后显示异常

### ISSUE THREAD

**Issue by wclyj** [pk910/PoWFaucet#216]
![1714196785619](https://github.com/pk910/PoWFaucet/assets/161707908/8afd90e1-2816-4d2c-ba5f-ce5d6c497906)
这是什么问题呢

**Comment by pk910** [comment]
Please write in English :)
I'm not sure what's wrong here,  can you provide a screenshot of the developer tools? 
You can usually open them with F12. Please provide a screenshot of the console tab,  I guess there's some error displayed.

**Comment by wclyj** [comment]
This issue has been resolved because I turned on the VPN. Thank you for using this faucet
