### ISSUE TITLE
Save the planet by removing rainbow cat animation

### ISSUE THREAD

**Issue by wen-moon-ser** [pk910/PoWFaucet#217]
Removing the cat GIF image (e.g. with adblock filter) increases hash rate by 10-20% in Chrome.

The cat is fun and all, but wastes electricity and reduces performance. It would be nice to either remove it entirely or to add a small "x" button at the corner of the image to remove it manually.

P.S. Note, that if you delete the image tag in dev tools, the hash rate decreases. This is because just opening dev tools adds some overhead by itself apparently.

**Comment by pk910** [comment]
lol, really!? 😂

Damn, GIFs indeed seem to impact performance quite much 😅
Yea,  I think a small x to stop the playback makes sense here.

**Comment by pk910** [comment]
Oops, the commit closed the issue :D
I've implemented a small button that replaces the gif with a static image.

The change is not rolled out on the public instances yet as there are currently too many people mining..
Will do in the coming days when there's a bit less activity :)

**Comment by moondogewen69** [comment]
@pk910 thank you ser! You are doing gods' work

(P.S. Wen token? :))
