### ISSUE TITLE
The faucet denied starting a session because your IP Address is marked as proxy range.

### ISSUE THREAD

**Issue by WLpower** [pk910/PoWFaucet#224]
Hello. Due to carelessness or rather ignorance, I did not turn off the VPN while mining the test Holešky PoW Faucet. The result was: "The faucet denied starting a session because your IP Address is marked as proxy range." Before that I was mining Sepolya and everything was fine. I am an ordinary WEB 3 beginner. “From the word” I am a complete beginner. I'm trying to test the Morph project and several other projects. I like it so much. I live in Ukraine, we can’t do without a VPN. Could you help restore mining? What information is required from me?
![Faucet 2024-05-09 091230](https://github.com/pk910/PoWFaucet/assets/138805660/a30f640c-246f-4482-9169-2dbf1b70365d)

**Comment by jmgalapon** [comment]
I have the same issue, how can i resolve this? I am not using any VPN of whatsoever

**Comment by pk910** [comment]
Should be fixed now.

**Comment by WLpower** [comment]
Thank you, I'm fine.
________________________________
От: pk910 ***@***.***>
Отправлено: 15 мая 2024 г. 22:19
Кому: pk910/PoWFaucet ***@***.***>
Копия: WLpower ***@***.***>; Author ***@***.***>
Тема: Re: [pk910/PoWFaucet] The faucet denied starting a session because your IP Address is marked as proxy range. (Issue #224)


Should be fixed now.

**Comment by jmgalapon** [comment]
Thank you, its now working on my end
