### ISSUE TITLE
My hashrate is 700 but i'm only getting 0.007 GöETH after 30 mins

### ISSUE THREAD

**Issue by wilderboz** [pk910/PoWFaucet#24]
My hashrate is 700 but i'm only getting 0.007 GöETH after 30 mins. What am I doing wrong?

**Comment by pk910** [comment]
Hmm, that doesn't sound normal.
Unfortunately my crystal ball is being repaired, so I can't tell you any details...
Maybe you can share some more information, like your ETH Address or IP Address.
Then there might be a chance to get some more details from the logs ;)

Normally such big reward reductions are described via a big red error message above the status panel.
Is there something that says "You're connecting from a hosting/proxy IP range?"

Another reason might be the farmer protection. Have you been mining a lot in the last days?
There is a lookback of 30 days per IP/address and mining is throttled if the total mined amount exceeds specific levels.
The faucet is not intended for farming / mass requesting. Goerli funds are rare and I'm trying to give everyone a chance to get some.
So if you've mined more than ~40ETH in the last month, that's probably the reason ;)
