### ISSUE TITLE
[CONCURRENCY_LIMIT] Only 1 concurrent sessions allowed per IP

### ISSUE THREAD

**Issue by Leooehh** [pk910/PoWFaucet#241]
Hey ! 
Getting the noted error even when the users are connecting from different IPs

Using Nginx with the recommended config in docs to run the static
and pm2 for the JS on a linux VPS.

The logs show every user connecting from the same IP ::1 .

I thought it might be caused by cloudflare but disabling it and working only with nginx didnt solve it either. 

Please let me know if any further info is required.

Thank you very much!

**Comment by pk910** [comment]
Heya @Leooehh,

You need to configure the number of proxy servers in front of the faucet:
```yaml
# number of http proxies in front of this faucet
httpProxyCount: 1
```

Use 1 if there's just the nginx server in front,  use 2 or more if there are additional proxy layers in your setup (cloudflare or so :))

**Comment by Leooehh** [comment]
That seems to be the solution. Thanki you very much for the quick resolution. will bother you again soon!!

Cheers,

**Comment by Leooehh** [comment]
Hey ! Its me again. hope you're doing well. quick question. Is there a possibility of changing the Mainnet token check's functionality to check a specific evm token instead of the native token? if so how? thank you very much for your guidance in advance.

**Comment by pk910** [comment]
Heya, this is not possible at the moment.
But it's not a big effort to make it possible :)
Please open a separate issue, then I'll gonna add that functionality

**Comment by Leooehh** [comment]
Thank you very much !!
Moved to INC#246
