### ISSUE TITLE
concurrent sessions error.

### ISSUE THREAD

**Issue by HuangNingPangZi** [pk910/PoWFaucet#252]
Hello, I'm getting the concurrent sessions error. Even though I'm not running any other sessions. Is there a way to get around this?

**Comment by pk910** [comment]
Heya,
The error means that someone from the same IP Address is already using the faucet.
This can happen if you're already mining with another device, or your ISP uses CG-NAT.

If you're sure you're not mining with another device, try restarting your router or try again at different times.
If that still doesn't work, try using a VPN.

Unfortunately there is not much I can do from my side, as removing the IP restriction would open the door for all kind of mass mining, which negatively affects all other users of the faucet.
