### ISSUE TITLE
Balance Display Shows 0 for Small Amounts.

### ISSUE THREAD

**Issue by Leooehh** [pk910/PoWFaucet#259]
Hey! Hope you're doing well.

I recently started experimenting with very low drop amounts (e.g., 0.00025 Ether). The issue I'm facing is that the balance displayed in the session or shown in the tweet (when using the share result button) is shown as 0. It only supports amounts down to 0.001, and anything smaller is displayed as 0.

Could you please guide me on how to fix this or if there are any workarounds? I really appreciate it in advance.

Please let me know if any further info is required Have a great day!

**Comment by pk910** [comment]
Heya @Leooehh,

Yea, this is unfortunately a bit of a technical debt in the faucet UI 😅
While all critical code paths use `BigInt` for balances. there are some non critical parts like the "human readable balance conversion" that still use normal `numbers`.
These numbers do not work well for utterly big or utterly small values, which leads to inaccurate balances :/

To get around these issues I've just hard-coded that the UI always rounds for 3 decimal places.

I can add a setting to make that configurable when I have time, this should work fine for about 6 decimal places max.
To support even smaller numbers, I'll need to make the whole UI code using `BigInt` consistently, which will probably take some more time :D

**Comment by Leooehh** [comment]
Hey !!

So update on this,

I found a "workaround" by replacing the 
```javascript
{toReadableAmount(this.props.faucetConfig.maxClaim, 
this.props.faucetConfig.faucetCoinDecimals, this.props.faucetConfig.faucetCoinSymbol)}
```
with the desired amount which is sort of a solution. I also tried changing the precision in ConvertHelpers.ts which worked but broke a lot of other things lol.

Overall this is only a experiment on providing gas fees to users for an L2 so I really wouldnt want you to spend too much time on it. If you think it would be a productive addition. having it in the config would be a blessing. 

Please let me know if there are any other ways to achieve this that I missed. Thank you very much!!
