### ISSUE TITLE
Wasting time

### ISSUE THREAD

**Issue by Asal-Vah** [pk910/PoWFaucet#266]
I started mining faucet (ETH Sepolia) for around 15 min. It's been completed but I got nothing.

**Comment by NanezX** [comment]
I started using it today and I got 0.5 and done. You are doing something wrong!

**Comment by willwinning** [comment]
> I started mining faucet (ETH Sepolia) for around 15 min. It's been completed but I got nothing.

come  here to buy

http://www.gaswap.top:8061/

**Comment by cryptotester** [comment]
I have a git passport score of 20ish... not too much, but not bad. Started mining and in less than 10 mins I got 4.5 Testnet ETH on Holesky. If you think infura and alchemy give 0.1 ETH per day... those other faucets are a waste of time. For this one to work well, work on your git passport score and you're good to go.
