### ISSUE TITLE
не работает кран

### ISSUE THREAD

**Issue by Kris61188** [pk910/PoWFaucet#270]
Добрый день! 
Когда ввожу номер кошелька и нажимаю на кнопку майнинга, то белый экран выхдит.
[снимок.pdf](https://github.com/user-attachments/files/16539547/default.pdf)
![image](https://github.com/user-attachments/assets/3b81db0a-1f53-4e9b-9b5b-72599e0fe0b6)

**Comment by pk910** [comment]
heya,
can you share more details about this issue?
What browser are you using / which OS?
Also please make a screenshot of errors shown in the developer console (hit F12 when being on the page)

**Comment by Kris61188** [comment]
google, windows
