### ISSUE TITLE
Polygon zkEVM: Cardona

### ISSUE THREAD

**Issue by Leooehh** [pk910/PoWFaucet#274]
Hey!!

I'm trying to set up a faucet on the Polygon zkEVM: Cardona network, but I'm running into an issue where the transaction fails with an "invalid sender" error. I've tried using different RPCs, but the problem persists.

Before diving deeper, I wanted to ask: is it currently possible to distribute tokens on the Polygon zkEVM: Cardona network using the same setup?

![image](https://github.com/user-attachments/assets/064354c0-c2fd-4443-85be-48bb960216a2)
![image](https://github.com/user-attachments/assets/485a2ce3-72b0-437f-9acd-46e33905559b)

Thank you very much in-advance !

**Comment by pk910** [comment]
Heya @Leooehh 

That's an interesting issue you've found there :D
I'm nor sure if the faucet works with the polygon network out of the box.

Can you try switching back to legacy transactions?
``ỳaml
# use legacy (non-eip1559) transaction type
# true: Type 0 (Legacy Transactions), false: Type 2 (EIP1559 Transactions)
ethLegacyTx: true
```

If that still doesn't work, there are probably some code changes needed.

I had similar problems getting the faucet running for a zkSync testnet earlier, 
so I ended up running a fork with their sdk to build transactions :/

**Comment by Leooehh** [comment]
Thanks for the tip @pk910 !

I switched it to legacy transactions as you suggested, and it worked like a charm.

Also big thanks for this project, it’s been super fun to operate!
