### ISSUE TITLE
How to use remote server to mine?

### ISSUE THREAD

**Issue by GeorgeLifinRell** [pk910/PoWFaucet#277]
I have a remote server and I'm unable to mine using it for my testing purposes. Help me how to create a request via command-line to mine and get sepoliaETH.

**Comment by pk910** [comment]
No.
This is clearly not supported nor wanted. 
Allowing remote mining would open the door for farmers with large mining farms and make the faucet unusable for regular users.
To prevent remote mining the faucet will also lower the rewards when connecting from a hosting IP Range.
