### ISSUE TITLE
Sir, I wanna Analyze this repository for personnel studying.

### ISSUE THREAD

**Issue by godtaehee** [pk910/PoWFaucet#3]
As you can see in title, I wanna know how to operate this faucet system.

I already done mining with it 1.2GoETH.

So I think this service provides mining system for user who wanna get Test Funds.

So I wanna go deep dive in this repository.

Any guide?

**Comment by pk910** [comment]
Heya,

You can easily run a copy of this project yourself.
Just follow the 'Run Yourself' section of the readme.

But I think you misinterpret what this faucet does. The "mining" here is not actually generating new coins. 
It's just a protection method to prevent the faucet from being drained by bots & farmers.
It's not working on anything useful. 
You have to deposit the funds that can then be "mined".

**Comment by godtaehee** [comment]
Thanks, you mean many bots & farmers abuse the faucet system, so You need to prevent from it. right???
