### ISSUE TITLE
Allow 7702 addresses to recieve funds

### ISSUE THREAD

**Issue by lightclient** [pk910/PoWFaucet#308]
Currently there is a ban on contract accounts receiving faucet funds based on this heuristic:

https://github.com/pk910/PoWFaucet/blob/ecdad2a3f3bef93f6424006895c92db6a1616c81/src/eth/EthWalletManager.ts#L282-L284

I think it should be updated to allow contracts with the `0xef0100` prefix.

**Comment by pk910** [comment]
Heya @lightclient,

I don't get why I need to whitelist the delegation prefix here?
As far as I understood 7702, this special code is only used while executing the transaction that holds the authorization and is cleared afterwards?
So the account should not have any code attached after execution completed, right?

If that's right, no account can ever have that code prefix for static calls (as it's not within a transaction execution context)..
