### ISSUE TITLE
How to remove current session for wallet address?

### ISSUE THREAD

**Issue by jhuang314** [pk910/PoWFaucet#309]
My computer crashed while mining the faucet, and now it looks like I'm unable to start a new session since the previous session wasn't closed prior to the crash. How do I abandon the previous session?

The error is "Could not start session" "[CONCURRENCY_LIMIT] Only 1 concurrent sessions allowed per wallet address"

**Comment by Elsiehwoods** [comment]
@jhuang314 you might need to manually close it if the platform allows for session management. If there's no direct way to do it, you might need to wait for the session to time out or contact support for help. They can usually clear the session on their end so you can start fresh. Have you tried restarting your computer and checking if the session resolves itself?

**Comment by jhuang314** [comment]
I had it in an incognito tab, so local cookies and sessions should have been cleared. I lost the session id in the url. The crash basically restarted the computer. So what you are telling me is that the server needs to clear session? How frequent is that?

**Comment by pk910** [comment]
yea, the previous comment was spam :D  github seems to have removed the whole account in meantime..

So yea, there is basically no way to cancel a session in this situation.
The faucet tries to restore sessions from localStorage, which doesn't work for you as you've been running in incognito mode.
You also won't find your session id in the browser history for the same reason.
Without knowledge of the session id, there is no way to control it in any way.

However, if the session is disconnected for more than 30mins, it's closed by the server and you should be able to start another one from the same ip address.
