### ISSUE TITLE
is there a way to use my GPU instead of my CPU to run the POW

### ISSUE THREAD

**Issue by TerrenceAddison** [pk910/PoWFaucet#31]
I seem to notice that it's running on my CPU and not on my GPU, I wonder if it's possible to change where it's running on?

**Comment by pk910** [comment]
Heya,

There is actually no real benefit of allowing mining via the gpu.
Sure, your gpu could do this kind of computation a lot faster.
But the mining stuff is just used as a protection method for the faucet.
It's not mining new coins or something like that (that's impossible on goerli).

So, if everyone would mine 100x faster, the reward would be 100x lower to meet the global daily limit again.

Besides of that it's unfortunately quite difficult to implement gpu based mining stuff within a browser ;)
