### ISSUE TITLE
Anything for Arbitrum Sepholia faucet?

### ISSUE THREAD

**Issue by Praveensenpai** [pk910/PoWFaucet#325]
I needed other repo similar to this which provides arbitrum seph or OP seph ETH

**Comment by jmynes** [comment]
@Praveensenpai 
Just bridge your mined Sepolia ETH to Arb Sepolia using the official Arbitrum Bridge:
https://bridge.arbitrum.io/?destinationChain=arbitrum-sepolia&sourceChain=sepolia

**Comment by Praveensenpai** [comment]
Thnx
