### ISSUE TITLE
BinanceBABT2 POIN NOT DETECTED Poins Calculation Different Between Passport and Sepolia PoW Faucet

### ISSUE THREAD

**Issue by angryone90** [pk910/PoWFaucet#328]
![brave_screenshot_sepolia-faucet pk910 de](https://github.com/user-attachments/assets/04028e40-f7bc-4d32-af3e-8cbedfc317a8)

i dont know why it happened. Why my Poin not added? I have done to verify Binance BAPT in passport an has been added in pasport poin. but in calculation Sepolia PoW Faucet is empty not showing. Please Fix it its not fair.

**Comment by MaxC19** [comment]
![Screenshot 2024-12-20 114502](https://github.com/user-attachments/assets/6dad2716-a636-4b57-920a-e680893046e1)
I experienced the same issue 
Needs to be fixed please

**Comment by MaxC19** [comment]
I even added the JSON file manually and it says incorrect

**Comment by pk910** [comment]
Heya, 
I've updated the stamp names on the faucet side :) Should be working again now.
I've also noticed the manual verification is a bit broken: https://github.com/pk910/PoWFaucet/issues/333

**Comment by MaxC19** [comment]
> Heya, I've updated the stamp names on the faucet side :) Should be working again now. I've also noticed the manual verification is a bit broken: #333

Bless up bro, it's working
