### ISSUE TITLE
Couldn't connect to node https://rpc.goerli.mudit.blog

### ISSUE THREAD

**Issue by TopgunZh** [pk910/PoWFaucet#33]
I run it myself, but have some error.

`2023-04-11 16:15:19  ERROR    Error loading wallet state for 0xCA9456991E0AA5d5321e88Bba44d405aAb401193: Error: CONNECTION ERROR: Couldn't connect to node https://rpc.goerli.mudit.blog.`
`2023-04-11 16:15:31  ERROR    Error loading wallet state for 0xCA9456991E0AA5d5321e88Bba44d405aAb401193: Error: CONNECTION ERROR: Couldn't connect to node https://rpc.goerli.mudit.blog.`

**Comment by pk910** [comment]
Heya @TopgunZh,
Yea, looks like the public RPC endpoint at `rpc.goerli.mudit.blog` is currently down..
You can change the RPC endpoint via the `ethRpcHost` [configuration option](https://github.com/pk910/PoWFaucet/blob/master/faucet-config.example.yaml#L54).
I suggest using a more reliable provider, like infura or alchemy, but you need to create a account with one of them yourself to get a api key :)
