### ISSUE TITLE
Sever lost when clicking the Start Mining button

### ISSUE THREAD

**Issue by yijie37** [pk910/PoWFaucet#34]
When I finish the captcha and click Start Mining button, the page says "Connection to faucet server lost. Reconnecting..." and dose not mine.

Os: Ubuntu 20.04
Browser: Chrome

![sepolia_pow](https://user-images.githubusercontent.com/4149610/231479876-1111132b-ebb3-4181-b2ce-31818f253658.png)

**Comment by pk910** [comment]
Hmm, are you using a proxy or firewall that blocks websocket connections?
When clicking on the Start Mining button, the faucet first tries to establish a websocket connection to the server, which seems to fail in your case.
Can you check the Developer Tools (press F12 key on the page) to see if there are any errors displayed?

**Comment by yijie37** [comment]
Hi, I was using a proxy. Now I see how it works. Thanks for the explanation!
