### ISSUE TITLE
Disabling EIP-1559 support / Invalid params error

### ISSUE THREAD

**Issue by rackrall** [pk910/PoWFaucet#37]
Hello. Is there any way to disable EIP-1559 support? I tried to change the code to work with regular transactions, but it seems to me transactions don't get sent when I modify the code to work with type-0 (legacy) transactions. This includes replacing maxPriorityFeePerGas and maxFeePerGas with gasPrice and also changing EthTx.FeeMarketEIP1559Transaction with EthTx.Transaction.

**Comment by pk910** [comment]
Heya,
Sorry, currently there is no support for legacy (type 0) transactions.
In theory you're right, and changing the function that calls `EthTx.FeeMarketEIP1559Transaction` should be enough.
But unfortunately there is one part missing: The fee estimation.

For EIP-1559 transactions I'm just setting a limit (maxPriorityFeePerGas/maxFeePerGas), and the network decides itself how much the transaction actually needs.
For legacy transactions I have to pre-estimate the fees myself.
That part of code is currently missing, so just changing it to `EthTx.Transaction` and using a static `gasPrice` will lead to paying a extremely high fee ;)

 I'll keep this issue open till I find some time to implement it properly.
 
 Just out of curiosity: What network are you trying to use the faucet for?

**Comment by rackrall** [comment]
I am using it for my friends private network. I implemented a quick hack just to get it working with type-0 transactions and another quick hack to support ERC-20 transfers instead of ETH :D

**Comment by pk910** [comment]
Uuh, that's cool 👍
ERC20 transfers have also been on my faucet-todo list for a long time :)
I'd appreciate if you push your hacks into a PR, I'll pick it up and do some cleanup :)

**Comment by rackrall** [comment]
Sure! I'll do it tomorrow 🥳

**Comment by pk910** [comment]
I've implemented a way to build legacy transactions.
You can enable it via `ethLegacyTx: true` in the config.
