### ISSUE TITLE
What the fuck is cloudflare here for?

### ISSUE THREAD

**Issue by naddika** [pk910/PoWFaucet#39]
How am I supposed to claim the coins?
![Screenshot_20230503_163924](https://user-images.githubusercontent.com/44301454/236028501-1c4f116f-d3f8-44c8-a1bb-22bd8610fff2.png)

**Comment by pk910** [comment]
Hmm, interesting... I haven't seen it failing that hard ever yet...

What kind of browser are you using?
Are you using any kind of VPN/Proxy server?

**Comment by pk910** [comment]
I've disabled the turnstile (cloudflare) captcha in the goerli instance for now.
Got more reports that it's not working properly..
