### ISSUE TITLE
Rewards Timeout

### ISSUE THREAD

**Issue by PhatJay76** [pk910/PoWFaucet#4]
This is utterly stupid.  I left this stupid system "mining" - to get back to "you didn't claim your rewards in time"  - What a complete waste of resources

**Comment by pk910** [comment]
Yea, I think it's fine you left :) Nobody forces you to use this faucet.

I think you should work on your attitude first of all. 
Apart of this I'll try to explain the technical background of this limitation - don't think you actually want to know, but it might be interesting for others.

There are two timeouts defined:
1. A mining timeout of 5h
2. A claiming timeout of 12h

So after mining for 5h, everyone has 7h left to claim the mined rewards.

There are several reasons for this timeout:
* I want to prevent mining on external (unowned) devices like servers. 
12h should be more than enough for a home mining scenario where you even might leave your computer running over night and claim on next morning, 
whereas scenarios where office computers are used at probably larger scale to mine during non office hours should be prevented.
* There is currently a limit of 2000 GöETH per day for the whole faucet to prevent it from being drained too fast.
The calculation to enforce this limit is unfortunately not very fair as it is based on the actual wallet balance. 
Claiming a reward directly affects the wallet balance and lowers the mining reward for others to meet the limit again.
I'd like to make the effect of late-claims (where mining sessions from days ago drain the wallet and affect current miners) as low as possible.
* There is a technical trade-off that forces me to use low claiming times (especially now as there is an abnormal high activity in the last days)
The trade-off comes from the fact that I'm not using any backend database for this faucet. 
All session data is managed in-memory or via signed session tokens.
But I still need to take track of claimed sessions to prevent double claiming during restarts.
This list of claimed sessions is stored on disk as a simple JSON file and shouldn't get too large for performance reasons. It is already very big as there are thousands of mining sessions every day and extending the claiming time would make it even bigger.

**Comment by PhatJay76** [comment]
Then you need to check your code. It had not even finished the 4 hour mining session before your stupid code took it back

**Comment by pk910** [comment]
Can you tell me your wallet address, then I can check the logs to see what was going on
