### ISSUE TITLE
Are you trying to steal funds?

### ISSUE THREAD

**Issue by manojkgorle** [pk910/PoWFaucet#40]
I entered your website, from chainlink faucet
As soon as I enter my Sepolia Eth balance went zero. I did not even approve any transaction

**Comment by pk910** [comment]
The faucet doesn't steal anything 😉
As you don't provide your private key/mnemonic anywhere, it's impossible to "steal" funds from your wallet without having you to sign something 😉

**Comment by manojkgorle** [comment]
but when i entered your website for the very first time, how did my funds vanish

**Comment by pk910** [comment]
idk, must be something different..
But it's definitely not related to the faucet. 
Was there an outgoing transaction?
Did you enter / share your privkey / mnemonic anywhere?

**Comment by manojkgorle** [comment]
no there is no outgoing transaction, I did not share any of my keys or mnemonic & neither are compromised.
I transferred all my remaining assets to a new account. The attack happened to steal only sepolia eth funds. Rest everything is safe
