### ISSUE TITLE
Reward Boost Not working 

### ISSUE THREAD

**Issue by RobeelZahid111** [pk910/PoWFaucet#42]
My reward boost not working I connected my passport and have very good score 
Earlier I have 500% Boost but now it is not working

**Comment by pk910** [comment]
What do you mean by "it is not working"?
What does the Boost-Dialog say?

**Comment by RobeelZahid111** [comment]
![image](https://github.com/pk910/PoWFaucet/assets/97405756/4af484da-ec6d-48f9-937f-f3250856e36b)

![image](https://github.com/pk910/PoWFaucet/assets/97405756/95808f25-fe0c-4375-9d3a-1a14a16ff694)


Please check the pictures Boost is showing 0% while I have passport and have good score

**Comment by pk910** [comment]
I see that's quite confusing.

The reason why your reward boost is still 0% is, that the stamps on your gitcoin passport expired on `2023-05-08`. 
Can you check https://passport.gitcoin.co/ ?  Their site should offer you a easy way to refresh the stamps :)

The UI of my faucet currently does not show any warning for expired stamps.. I'll add that to make it more clear :)

**Comment by RobeelZahid111** [comment]
My stamps are also updated check this [image: image.png]

**Comment by RobeelZahid111** [comment]
![image](https://github.com/pk910/PoWFaucet/assets/97405756/6a9122df-12ca-44bb-8c02-db3e2fdc50d6)

Sorry to say but my all stamps are updated too

**Comment by pk910** [comment]
Hmm, the faucet still gets the expired stamps from the passport api :/
Can you try copy/pasting the passport JSON manually?
You can find that JSON on the passport page via the </> button in the top right corner.
Then send it to the faucet via the "Verify Manually" Button in the Boost Details dialog.

**Comment by RobeelZahid111** [comment]
Thank you so much man 
It worked I am so happy

**Comment by pk910** [comment]
I'll keep this open to implement a proper fix for the UI.
I think the faucet should display a error message when it gets only the expired stamps from the api...

It's unfortunately quite hard to develop & test this, as I can't easily reproduce the specific situation...
Luckily the stamps on my own passport expire in 14 days too - so I guess I can reproduce this & implement a proper error message then :)

**Comment by RobeelZahid111** [comment]
Okay boss

**Comment by pk910** [comment]
I've re-implemented a big part of the passport stuff.
It's now using a hopefully more reliable api :)

I've also got notified about a bug that allowed reusing the same stamp on multiple passports. 
That should now be fixed too :)
The UI update includes a Expired mark, so it's easy to see which stamp expired.
