### ISSUE TITLE
[bug] coinbase stamp rewards has no score

### ISSUE THREAD

**Issue by Elliott-Green** [pk910/PoWFaucet#45]
GIVEN I have a coinbase stamp in git passport
WHEN I copy/paste my JSON into the verification parser
THEN I expect a score of at least 1 
OR to label it with an actual non score of 0

<img width="338" alt="image" src="https://github.com/pk910/PoWFaucet/assets/10979087/1cb1798d-8848-4784-9229-2e2e56f7c597">

**Comment by pk910** [comment]
Thanks for reporting :)
Yea, there was no score for that stamp. 
That stamp must have been added recently... I've added it with a score of 1 now.

I think it's kind of a feature that these missing stamps are displayed without a score :D
If I'd just show them as 0, most people would think it's "normal" like that and I wouldn't ever get noticed about the missing score ;)
