### ISSUE TITLE
did not receiv ETH

### ISSUE THREAD

**Issue by ShahramJalili** [pk910/PoWFaucet#46]
![C](https://github.com/pk910/PoWFaucet/assets/133899646/f945c5e8-938d-40c7-b4e5-f009b70de067)
![Cla](https://github.com/pk910/PoWFaucet/assets/133899646/812a0cc1-2dd3-4beb-be75-fb06f81575ef)
![Cla](https://github.com/pk910/PoWFaucet/assets/133899646/3e91ee58-dfe1-4b79-8132-2dcbe3e91994)
![C](https://github.com/pk910/PoWFaucet/assets/133899646/1fb036b0-a441-4e92-a3f9-e1fc4625ccd8)

**Comment by ShahramJalili** [comment]
please tell me the problem

**Comment by pk910** [comment]
https://sepolia.etherscan.io/address/0x22685edb4AB764E762EAd4d8536714c8d475b641
I don't see any problems.. It's in your account on the sepolia network.

**Comment by ShahramJalili** [comment]
![Clai](https://github.com/pk910/PoWFaucet/assets/133899646/b9e93ecb-29e9-4e57-a570-6a9f93fb3a86)

**Comment by ShahramJalili** [comment]
any problem with my wallet?

**Comment by ShahramJalili** [comment]
thankyou so much
for investing

**Comment by pk910** [comment]
testnet funds do not have any value ;)
testnets are intended to be free, so developers can test their contracts somewhere without investing real money.

**Comment by ShahramJalili** [comment]
i got ot. do you know any mining sites ?

**Comment by pk910** [comment]
ETH changed its consensus mechanism from proof-of-work to proof-of-stake a year ago, so there is no way to mine new ETH anymore.
