### ISSUE TITLE
reCAPTCHA will not validate when claiming funds

### ISSUE THREAD

**Issue by Fluffybird39** [pk910/PoWFaucet#47]
I've noticed the issue for a couple days, where it took more tries than usual to validate (about 10 times).  However, today 5/30/2023, I can't validate after 30 tries. After successfully clicking all boxes the reCAPTCHA asked to click on, 'Please Try Again' is returned. See attached.  I'm not having issues with any other CATCHA in web3.
![Screen Shot 05-30-23 at 08 51 AM](https://github.com/pk910/PoWFaucet/assets/128872487/2761ecf5-b88c-456e-b6d2-55bbf47ece4c)

**Comment by pk910** [comment]
Heya,
Thanks for your report.

Does the captcha actually show a green tick after solving these image challenges?
![image](https://github.com/pk910/PoWFaucet/assets/491045/c828563f-bdbe-4837-9ef7-5c9e75a12b28)

I'm trying to reproduce it somehow, but all my tries have been successful so far on first try 😅
![image](https://github.com/pk910/PoWFaucet/assets/491045/2e99fd54-567e-4fda-8f1e-7dc3cbd646c7)

Is it the same on session start too?

**Comment by Fluffybird39** [comment]
It looks like this is working again.  I don't believe I saw the green check mark after successfully solving the image challenge. I only had the issue when claiming the test tokens, the session start hasn't been an issue.

**Comment by pk910** [comment]
Great it's working again 👍

I know these captchas can sometimes be quite challenging.
It could all be so much easier without all these bots around...

If it continually fails you could also try refreshing the page, so the captcha gets completely reloaded.
The claim is not lost, the dialog is displayed again on refresh :)

I'll keep it in mind and will take further action when there are more reports :)

**Comment by pk910** [comment]
Hmm, I've tried again several times with false inputs to trigger the "Please try again" message. 
But even after that, I've been able to get the green tick via the next 1-2 correct challenges...

**Comment by pk910** [comment]
I've done some more testing with the help of some AI tool that solves these captchas automatically.
After running it for some time and solving about 100 captchas with a pretty high success rate (>80%), I'm now getting a lot harder and more challenges.
I think the reCaptcha system has some kind of IP based reputation system behind,  so IPs that solve a lot of captchas (and/or do a lot of failures) are getting harder challenges.
I guess you might mitigate that by restarting your router, so you hopefully get a new IP address, that is not recognized by reCaptcha in that way :)

I think the captcha works in general, however, I think I might even remove these captchas entirely soon.. 
That AI tool I've discovered a few hours ago is impressive and makes these kinds of captchas completely worthless...
It's open source and ready to use in all recent browsers... I'm not gonna share a link for obvious reasons :D

**Comment by Fluffybird39** [comment]
Thank you! I'll try resetting the modem.  I've been doing significant L2 testing so I've doing captchas multiple times per day.
