### ISSUE TITLE
Can't mine

### ISSUE THREAD

**Issue by Loskelly7** [pk910/PoWFaucet#49]
When ever i click on starting mining, it will pop up that I am connecting from the hosting IP

I don't understand what it really means

**Comment by pk910** [comment]
Heya @Loskelly7,

First of all, sorry for that. That restriction you're facing is there to keep out bots.
It is not intended to prevent "normal users" from mining, but unfortunately there are some false-positives that I have no control of.

Basically the error tells you that the faucet detected that you're connecting from a "hosting IP range".
Normally, only IP's that are used in datacenters by servers are marked that way.

May I ask what IP you're connecting from? https://whatismyipaddress.com/

To workaround your problem you can try the following:
* If you're using any vpn or proxy service, turn that off.
* Restart your router to get another IP Address, that is hopefully not falsely marked as "hosting IP"

**Comment by flatironman88** [comment]
ISSUE: when I try to connect it says "Could not get balance of Wallet 0x6317910E0668Dc46cf0BDF7a692fb782A014680e: Error: CONNECTION ERROR: Couldn't connect to node http://10.16.71.104:8555/."

**Comment by Craptor0** [comment]
Could not get balance of Wallet 0x694eA6D042A9D5C12bcDB55A5EBb2499ecC89210: Error: CONNECTION ERROR: Couldn't connect to node http://10.16.71.104:8555/. can someone help please
