### ISSUE TITLE
mumbai support?

### ISSUE THREAD

**Issue by dcsan** [pk910/PoWFaucet#5]
is adding support for polygon network / mumbai something that can be done on the config level or is it a much bigger project?

**Comment by pk910** [comment]
Heya,
It should be compatible and just a config thing :)
But I don't have any mumbai funds and don't know who to contact to get a bigger chunk of funds to run an instance.

**Comment by dcsan** [comment]
do you mean some funds to start up the system?

isn't the point of running such a node that we could grind away to mine some mumbai tokens?

**Comment by pk910** [comment]
No.
This faucet does not generate new coins with the "mining" process.
That's impossible on networks that run on PoS.
The mining involved is just a way to prevent anyone from requesting big amounts of funds and draining the faucet wallet.
All funds the faucet pays out have to be deposited by the owner of the faucet before.

**Comment by warengonzaga** [comment]
Hmm, I see, how does the mining work btw @pk910? I'm interested to learn more.
