### ISSUE TITLE
The faucet could not connect to the network RPC

### ISSUE THREAD

**Issue by nguyenanh29** [pk910/PoWFaucet#50]
Take a weekend break?

**Comment by aladyn-web** [comment]
habe das gleiche problem. Was kann man machen?

**Comment by flatironman88** [comment]
ISSUE: when I try to connect it says "Could not get balance of Wallet 0x6317910E0668Dc46cf0BDF7a692fb782A014680e: Error: CONNECTION ERROR: Couldn't connect to node http://10.16.71.104:8555/."

**Comment by Craptor0** [comment]
i havent received the 0.6 gEth i mined yesterday yet and now when i try to connect it gives Could not get balance of Wallet 0x694eA6D042A9D5C12bcDB55A5EBb2499ecC89210: Error: CONNECTION ERROR: Couldn't connect to node http://10.16.71.104:8555/. 
please help

**Comment by Gulfie9890** [comment]
Same problem... Is there any update?

**Comment by pk910** [comment]
Meeh, sorry guys, just noticed the issue 🙄
It looks like my RPC node is down.. 
I've been traveling over the weekend, but will fix it asap when back home tomorrow...
Sorry for the trouble.. Such things always need to happen when I'm not home 😐

**Comment by pk910** [comment]
Fixed it remotely 🎉

https://play.google.com/store/apps/details?id=com.server.auditor.ssh.client
This app is awesome 😆

**Comment by pk910** [comment]
Closing this issue now.
Looks like my remote fixing attempt worked very well.
All priviously failed transactions have been sent out to the switched over RPC. No rewards have been lost. 

New sessions couldn't be started during the RPC downtime, which I think is the best behavior, when the faucet isn't working properly for some reason.

**Comment by Gulfie9890** [comment]
> Closing this issue now. Looks like my remote fixing attempt worked very well. All priviously failed transactions have been sent out to the switched over RPC. No rewards have been lost.
> 
> New sessions couldn't be started during the RPC downtime, which I think is the best behavior, when the faucet isn't working properly for some reason.

Thanks for your effort sir!
