### ISSUE TITLE
Claim failed

### ISSUE THREAD

**Issue by alehfedaruk** [pk910/PoWFaucet#51]
Nevermind if it was mentioned before. I didnt find it.

So if I claim before captcha loaded it seems to me that the params are not passed correctly, or smth is missing 

![Claim failed](https://github.com/pk910/PoWFaucet/assets/43803443/a560715f-a5ac-409d-ada7-9fc5cd26085d)

**Comment by pk910** [comment]
thanks for reporting, this was affecting all error messages on the claim page 😅
fixed it
