### ISSUE TITLE
Ip blocked

### ISSUE THREAD

**Issue by shubzok** [pk910/PoWFaucet#55]
I am getting this message cant mine goerili eth [IPINFO_RESTRICTION] IP Blocked: You're connecting from a proxy IP range.

**Comment by abbacialla** [comment]
i think u are using rdp or vps

**Comment by pk910** [comment]
Yea. That might be a reason.

Unfortunately it's nothing I can change. 
I know there are some false positives in the proxy/hosting detection from [ip-api.com](https://ip-api.com)
However, it works quite well to filter out farmers that use hundreds of rented VPNs to farm the faucet 🙄

If your IP is falsely detected as proxy or hosting IP, and you're sure that you're not using a proxy or VPN, 
restart your router to get a new IP from your ISP. Chances are high that the new IP isn't listed as proxy range.
