### ISSUE TITLE
Funds not coming to faucet wallet after I stop mining

### ISSUE THREAD

**Issue by Bhavya6187** [pk910/PoWFaucet#57]
I got the faucet running locally and successfully mining. I loaded the private key from facet config and sent 1 Goerli Eth to fund the faucet wallet. When I stop the faucet after mining 0.5ETH to claim the rewards, and then transfer to other wallet, I can see that I lose the Goerli ETH that I initially seeded the account with, and now the faucet wallet has only 0.5ETH.

Is there a setting which I am missing here that needs to change, so that the faucet wallet gets the mined ETH once I stop the mining?

**Comment by pk910** [comment]
Huh, that sounds strange 😅
Which wallet did you run the faucet on? Can you share the wallet address?

The faucet cannot generate new GoETH. There is no way to do that.
So if you pre-fund your faucet wallet with 1GoETH, and request 0.5ETH from it, then there is only 0.5ETH left (excl. some fees).

**Comment by Bhavya6187** [comment]
This is my faucet address - https://goerli.etherscan.io/address/0xD544F082e7052D2617469800d7637EBFf8A2b0a9

On the localhost, it shows as mining, and I can see my CPU usage heavily spiking. However I am not able to claim the GoEth when I stop mining and claim. Not sure where that goes after I stop. The transfer of ETH happens from the faucet wallet using the 1ETH I initially funded it with.

**Comment by pk910** [comment]
Looking at the wallet I see various transfers back to your wallet, so it looks like it is working properly?

I think there is a misunderstanding of what the faucet does. This "mining" stuff is not really mining for new coins. 
The mining requirement is used as a protection method to prevent mass requests from bots or so.
The faucet can only distribute what you've sent in before. Even if the page shows 10 ETH at some time, you'll never be able to get these 10 ETH if you didn't send that amount to the faucet wallet before.

**Comment by Bhavya6187** [comment]
Thanks for clarifying my misunderstanding!
