### ISSUE TITLE
Typo in Operator-Wiki

### ISSUE THREAD

**Issue by M2l2koPOWER** [pk910/PoWFaucet#59]
https://github.com/pk910/PoWFaucet/wiki/Operator-Wiki#use-release-with-local-nodejs

The typo is related to the command to unpack the archive via `tar -xfz`. Using these flags causes an error, you should use `tar -xzf`

![image](https://github.com/pk910/PoWFaucet/assets/23089294/7d53f1ae-8817-45f4-8d0b-d4203abe4e5f)

**Comment by pk910** [comment]
Heya, thanks for the hint :D
I think I've used `-xfz` ever since.. 
Didn't know that there is a inconsistency between distros..

**Comment by pk910** [comment]
and fixed :)
