### ISSUE TITLE
Concurrent session limit reached

### ISSUE THREAD

**Issue by bekatan** [pk910/PoWFaucet#6]
Hi,
I was mining for a little and then stopped and claimed some rewards earlier. But now I can't start mining again. I am getting "Concurrent session limit reached" although I don't have any that I am aware of.

I am guessing there is a session in the servers that is not terminated yet. What can I do?

**Comment by pk910** [comment]
Heya @bekatan,
thanks for the report.

The concurrency limit is applied on IP Level (so only 1 session is allowed per public IP).
Are you behind a CG-NAT or are you using a public network?

Technically it shouldn't be possible that a closed session is "stuck" and blocks you from opening a new one as there is no database behind. The Faucet iterates all other active connections to see if there is another mining session from the same IP address.

If you're sure there is no-one else mining from your IP, and you still see the error, 
please share your wallet or IP address, so I can take a look into the logs to see what was going on.

**Comment by bekatan** [comment]
Yes, it was the school network. Turns out it was on the IP level, because I tried it on a different network and it worked normally. 

Thanks for the reply though.
