### ISSUE TITLE
IP blocked because of region ? (Asia)

### ISSUE THREAD

**Issue by kanissell** [pk910/PoWFaucet#60]
Hi,

I try to use the miner but Everytime I get the ip blocked message.

is it possible that the ip range of Vietnam is blocked ? 

I don’t use any vps or vpn

**Comment by pk910** [comment]
Heya,

The faucet blocks IP Ranges when being excessively used for farming the faucet. 
(when exceeding more than 100 distinct IP's within a specific period of time)

It's not specifically blocking a country or region,  it's rather blocking the whole /16 subnet for some time.
However, these blocks are non-permanent, and should be automatically removed after a day or two.

If you're "permanently" blocked, there is probably someone in your area excessively abusing the faucet.
I can't really help in that situation.  The faucet tries to protect itself here..
