### ISSUE TITLE
Can not click "prove"

### ISSUE THREAD

**Issue by DaC1989** [pk910/PoWFaucet#65]
I don't know what is ZKEdDSA Proof, but after my first login, I couldn't click the "Prove" button,
what should I do?
![1703605151800](https://github.com/pk910/PoWFaucet/assets/25810981/cd3038c8-4960-4cb1-b496-4f100d70dc43)

**Comment by pk910** [comment]
The zupass authentication is only for DevConnect attendees.
If you have been at the event, you have probably bought a ticket, which can be used to get a one-time drop.

It looks like you don't have a devconnect ticket ("No eligible PCDs found"), and therefore you can't prove that you have one ;)

**Comment by jokoamir210515** [comment]
Aprove

**Comment by jokoamir210515** [comment]
Prove

**Comment by jokoamir210515** [comment]
![Screenshot_2024-02-02-21-44-47-593_com kiwibrowser browser](https://github.com/pk910/PoWFaucet/assets/78344818/ee86a878-0dd4-409e-a5e9-5f059bc57923)

**Comment by jokoamir210515** [comment]
I don't know what is ZKEdDSA Proof, but after my first login, I couldn't click the "Prove" button,
what should I do?

**Comment by pk910** [comment]
The zupass authentication is only for people that have been at DevConnect in November last year.
Zupass was used for the ticketing there. If you have bought a ticket for the event, you'd have got a zupass login.

**Comment by jokoamir210515** [comment]
I bought a ticket in November last year but I didn't get a ticket
