### ISSUE TITLE
Goerli Claim Error

### ISSUE THREAD

**Issue by j0n77777** [pk910/PoWFaucet#80]
Getting the following error when I try to claim Goerli: "Claim failed: Processing Exception: InvalidResponseError: Returned error: insufficient funds for gas * price + value: balance 1623885893655303811800, queued cost 1623854779765500000000, tx cost 1021000000000000000, overshot 989886110196188200"

**Comment by pk910** [comment]
Fixed :)
My goerli ethereum client pair hung up for some reason :/
Time to let goerli die :D
